--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: postgres
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: postgres
  template: 
    metadata: 
      labels: 
        app: postgres
    spec: 
      containers: 
        - 
          envFrom: 
            - 
              configMapRef: 
                name: postgres-config
          image: "postgres:latest"
          imagePullPolicy: IfNotPresent
          name: postgres
          volumeMounts: 
            - 
              mountPath: /var/lib/postgresql/data
              name: postgredb
      volumes: 
        - 
          name: postgredb
          persistentVolumeClaim: 
            claimName: postgres-pv-claim
